routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::redirect('/', '/login');

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('companies', 'CompanyController');
    Route::resource('departments', 'DepartmentController');
    Route::resource('employees', 'EmployeeController');
});

app/Employee.php
<?php

namespace App;

use App\Department;
use App\EmployeeHistory;
use App\EmployeeStatus;
use App\Traits\HasHistory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes, HasHistory;

    protected $fillable = [
        'first_name','last_name','position','contact_number','email','full_address','status_id'
    ];


    public function status()
    {
        return $this->belongsTo(EmployeeStatus::class, 'status_id');
    }

    public function departments()
    {
        return $this->belongsToMany(Department::class, 'department_employees');
    }

    public function histories()
    {
        return $this->hasMany(EmployeeHistory::class, 'employee_id');
    }

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Http\Requests\Employee\StoreRequest;
use App\Http\Requests\Employee\UpdateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EmployeeController extends Controller
{
    protected $page = 10;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::query()->orderByDesc('created_at')
            ->with('departments')
            ->paginate($this->page);

        return view('pages.employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        DB::beginTransaction();
        try {
            $employee = Employee::create(array_merge($request->validated(), ['status_id' => 1]));
            
            $employee->createHistory('added');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('employees.index')->with('error', 'Error storing employee details');
        }

        DB::commit();

        return redirect()->route('employees.index')->with('success', 'Employee is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('pages.employee.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('pages.employee.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Employee $employee)
    {
        DB::beginTransaction();
        try {
            $employee->fill($request->validated());
            $employee->save();

            $employee->createHistory('updated');

            $employee->employees()->sync($request->department_ids);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('employees.index')->with('error', 'Error updating employee details');
        }

        DB::commit();

        return redirect()->route('employees.index')->with('success', 'Employee is updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        DB::beginTransaction();
        try {
            $employee->delete();

            $employee->createHistory('deleted');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('employees.index')->with('error', 'Error deleting employee');
        }

        DB::commit();

        return redirect()->route('employees.index')->with('success', 'Employee is deleted successfully');
    }
}

resources/views/pages/employee/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Employee')

@section('content_header')
    <h1 class="m-0 text-dark">Employees</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">New Employee</h3>
                  </div>
                <div class="card-body">
                    <form action="{{ route('employees.store') }}" method="post">
                        @csrf
                        @method('post')
                        <x-adminlte-input name="first_name" label="First name" placeholder="First name"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-input name="last_name" label="Last name" placeholder="Last name"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-input name="contact_number" label="Contact number" placeholder="Contact number"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-input name="position" label="Position" placeholder="Position"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-input name="email" label="Email" placeholder="Email"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-input name="full_address" label="Address" placeholder="address"
                                fgroup-class="col-md-12"/>


                        <x-adminlte-button  type="submit" label="submit" class="ml-2" theme="primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/employee/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Employee')

@section('content_header')
    <h1 class="m-0 text-dark">Employees</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Employee</h3>
                  </div>
                <div class="card-body">
                    <form action="{{ route('employees.update', $employee->id) }}" method="post">
                        @csrf
                        @method('put')
                        <x-adminlte-input name="first_name" label="First name" placeholder="First name"
                                fgroup-class="col-md-12" value={{ $employee->firt_name}}/>

                        <x-adminlte-input name="last_name" label="Last name" placeholder="Last name"
                                fgroup-class="col-md-12" value={{ $employee->last_name}}/>

                        <x-adminlte-input name="contact_number" label="Contact number" placeholder="Contact number"
                                fgroup-class="col-md-12" value={{ $employee->contact_number}}/>

                        <x-adminlte-input name="position" label="Position" placeholder="Position"
                                fgroup-class="col-md-12" value={{ $employee->position}}/>

                        <x-adminlte-input name="email" label="Email" placeholder="Email"
                                fgroup-class="col-md-12" value={{ $employee->email}}/>

                        <x-adminlte-input name="full_address" label="Address" placeholder="address"
                                fgroup-class="col-md-12" value={{ $employee->full_address}}/>


                        <x-adminlte-button  type="submit" label="submit" class="ml-2" theme="primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/employee/index.blade.php
@extends('adminlte::page')

@section('title', 'Employees')

@section('content_header')
    <h1 class="m-0 text-dark">Employees</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Employees List</h3>
                    <div class="card-tools">
                        <a href="{{ route('employees.create') }}" class="btn btn-primary">Create</a>
                    </div>
                  </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Position</th>
                                    <th>Email</th>
                                    <th>Contact Number</th>
                                    <th>Address</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($employees as $employee)
                                    <tr>
                                        <td>{{ $employee->full_name }}</td>
                                        <td>{{ $employee->position }}</td>
                                        <td>{{ $employee->email }}</td>
                                        <td>{{ $employee->contact_number }}</td>
                                        <td>{{ $employee->address }}</td>
                                        <td>
                                            <a href="{{ route('employees.edit',$employee->id) }}" class="btn btn-info">Edit</a>
                                            <a href="{{ route('employees.show',$employee->id) }}" class="btn btn-info">Show</a>
                                            
                                            <form  action="{{ route('employees.destroy',$employee->id) }}" class="submit-delete-form" method="POST" style="display: inline;"> @csrf @method('delete')
                                                <a href="#" class="btn btn-danger delete">Delete</a>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center">No records</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $employees->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
<script type="text/javascript">

    $('table tbody').on('click','.delete',function(e){
        e.preventDefault();
        var url = $(this).data('route');
        var that = this;

        Swal.fire({
            icon: 'info',
            title: 'Delete Department',
            text: 'Do you really want to delete?',
            showCancelButton: true,
            showConfirmButton:true,
            preConfirm: (res) => {
                that.closest('form').submit();
            }
        })
    });
    
    
</script>
@endpush