routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::redirect('/', '/login');

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('companies', 'CompanyController');
    Route::resource('departments', 'DepartmentController');
    Route::resource('employees', 'EmployeeController');
});

app/Department.php
<?php

namespace App;

use App\Company;
use App\DepartmentHistory;
use App\DepartmentStatus;
use App\Employee;
use App\Traits\HasHistory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Department extends Model
{
    use SoftDeletes, HasHistory;

    protected $fillable = [
        'name', 'description','status_id'
    ];


    public function status()
    {
        return $this->belongsTo(DepartmentStatus::class, 'status_id');
    }


    public function histories()
    {
        return $this->hasMany(DepartmentHistory::class, 'department_id');
    }

    public function companies()
    {
        return $this->belongsToMany(Company::class, 'company_departments');
    }

    public function employees()
    {
        return $this->belongsToMany(Employee::class, 'department_employees');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\Http\Requests\Department\StoreRequest;
use App\Http\Requests\Department\UpdateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DepartmentController extends Controller
{
    protected $page = 10;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Department::query()->orderByDesc('created_at')
            ->with('employees')
            ->paginate($this->page);

        return view('pages.department.index', compact('departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        DB::beginTransaction();
        try {
            $department = Department::create(array_merge($request->validated(), ['status_id' => 1]));
            
            $department->createHistory('added');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('departments.index')->with('error', 'Error storing department details');
        }

        DB::commit();

        return redirect()->route('departments.index')->with('success', 'Department is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        return view('pages.department.show', compact('department'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        return view('pages.department.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Department $department)
    {
        DB::beginTransaction();
        try {
            $department->fill($request->validated());
            $department->save();

            $department->createHistory('updated');

            $department->employees()->sync($request->employee_ids);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('departments.index')->with('error', 'Error updating department details');
        }

        DB::commit();

        return redirect()->route('departments.index')->with('success', 'Department is updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        DB::beginTransaction();
        try {
            $department->delete();

            $department->createHistory('deleted');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('departments.index')->with('error', 'Error deleting department');
        }

        DB::commit();

        return redirect()->route('departments.index')->with('success', 'Department is deleted successfully');
    }
}

resources/views/pages/department/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Department')

@section('content_header')
    <h1 class="m-0 text-dark">Department</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">New Department</h3>
                  </div>
                <div class="card-body">
                    <form action="{{ route('departments.store') }}" method="post">
                        @csrf
                        @method('post')
                        <x-adminlte-input name="name" label="Name" placeholder="name"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-textarea name="description" fgroup-class="col-md-12"  label="Description" placeholder="description"/>

                        <x-adminlte-button  type="submit" label="submit" class="ml-2" theme="primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/department/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Department')

@section('content_header')
    <h1 class="m-0 text-dark">Departments</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Department - {{ $department->name }}</h3>
                  </div>
                <div class="card-body">
                    <form action="{{ route('departments.update',$department->id) }}" method="post">
                        @csrf
                        @method('put')
                        <x-adminlte-input name="name" label="Name" placeholder="name"
                                fgroup-class="col-md-12" value="{{ $department->name }}"/>

                        <x-adminlte-textarea name="description" fgroup-class="col-md-12"  label="Description" placeholder="description">{{ $department->description }}</x-adminlte-textarea>

                        <x-adminlte-select name="status_id" fgroup-class="col-md-12" label="Status">
                            <x-adminlte-options :options="[1 => 'Active', 0 => 'Inactive']" selected="{{ $department->status_id}}"
                                empty-option="Select one"/>
                        </x-adminlte-select>

                        <x-adminlte-button  type="submit" label="submit" class="ml-2" theme="primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/department/index.blade.php
@extends('adminlte::page')

@section('title', 'Departments')

@section('content_header')
    <h1 class="m-0 text-dark">Departments</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Departments List</h3>
                    <div class="card-tools">
                        <a href="{{ route('departments.create') }}" class="btn btn-primary">Create</a>
                    </div>
                  </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($departments as $department)
                                    <tr>
                                        <td>{{ $department->name }}</td>
                                        <td>{{ $department->description }}</td>
                                        <td>{{ $department->status->name }}</td>
                                        <td>
                                            <a href="{{ route('departments.edit',$department->id) }}" class="btn btn-info">Edit</a>
                                            <a href="{{ route('departments.show',$department->id) }}" class="btn btn-info">Show</a>
                                            
                                            <form  action="{{ route('departments.destroy',$department->id) }}" class="submit-delete-form" method="POST" style="display: inline;"> @csrf @method('delete')
                                                <a href="#" class="btn btn-danger delete">Delete</a>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4" class="text-center">No records</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $departments->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
<script type="text/javascript">

    $('table tbody').on('click','.delete',function(e){
        e.preventDefault();
        var url = $(this).data('route');
        var that = this;

        Swal.fire({
            icon: 'info',
            title: 'Delete Department',
            text: 'Do you really want to delete?',
            showCancelButton: true,
            showConfirmButton:true,
            preConfirm: (res) => {
                that.closest('form').submit();
            }
        })
    });
    
    
</script>
@endpush

resources/views/pages/department/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Department')

@section('content_header')
    <h1 class="m-0 text-dark">Departments</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Departments Details - {{ $department->name }}</h3>
                  </div>
                <div class="card-body">
                        <x-adminlte-input name="name" label="Name" placeholder="name"
                                fgroup-class="col-md-12" value="{{ $department->name }}" readonly/>

                        <x-adminlte-textarea name="description" fgroup-class="col-md-12"  label="Description" placeholder="description" readonly>{{ $department->description }}</x-adminlte-textarea>

                        <x-adminlte-select readonly name="status_id" fgroup-class="col-md-12" label="Status">
                            <x-adminlte-options :options="[1 => 'Active', 0 => 'Inactive']" selected="{{ $department->status_id}}"
                                empty-option="Select one"/>
                        </x-adminlte-select>

                        <x-adminlte-input name="name" label="Created At" placeholder="name"
                                fgroup-class="col-md-12" value="{{ $department->created_at }}" readonly/>

                        <a href="{{ route('departments.index')}}" class="btn btn-default ml-2">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop