routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::redirect('/', '/login');

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('companies', 'CompanyController');
    Route::resource('departments', 'DepartmentController');
    Route::resource('employees', 'EmployeeController');
});

app/Company.php
<?php

namespace App;

use App\CompanyDepartment;
use App\CompanyHistory;
use App\Department;
use App\Traits\HasHistory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes, HasHistory;

    protected $fillable = [
        'name', 'description','status_id'
    ];


    public function status()
    {
        return $this->belongsTo(CompanyStatus::class, 'status_id');
    }


    public function histories()
    {
        return $this->hasMany(CompanyHistory::class, 'company_id');
    }

    public function companyDepartments()
    {
        return $this->hasMany(CompanyDepartment::class, 'company_id');
    }

    public function departments()
    {
        return $this->belongsToMany(Department::class, 'company_departments');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Http\Requests\Company\StoreRequest;
use App\Http\Requests\Company\UpdateRequest;
use App\Mail\NewCompany;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class CompanyController extends Controller
{
    protected $page = 10;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::query()->orderByDesc('created_at')
            ->with('departments')
            ->paginate($this->page);

        return view('pages.company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        DB::beginTransaction();
        try {
            $company = Company::create(array_merge($request->validated(), ['status_id' => 1]));
            $company->createHistory('added');

            Mail::to(auth()->user()->email)->queue(
                new NewCompany([
                    'company_name' => $company->name,
                    'created_by'   => auth()->user()->name,
                ])
            );
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('companies.index')->with('error', 'Error storing company details');
        }

        DB::commit();

        return redirect()->route('companies.index')->with('success', 'Company is added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        return view('pages.company.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('pages.company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Company $company)
    {
        DB::beginTransaction();
        try {
            $company->fill($request->validated());
            $company->save();

            $company->createHistory('updated');

            $company->departments()->sync($request->department_ids);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('companies.index')->with('error', 'Error updating company details');
        }

        DB::commit();

        return redirect()->route('companies.index')->with('success', 'Company is updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        DB::beginTransaction();
        try {
            $company->delete();

            $company->createHistory('deleted');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('companies.index')->with('error', 'Error deleting company');
        }

        DB::commit();

        return redirect()->route('companies.index')->with('success', 'Company is deleted successfully');
    }
}

resources/views/pages/company/create.blade.php
@extends('adminlte::page')

@section('title', 'New Company')

@section('content_header')
    <h1 class="m-0 text-dark">Companies</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">New Company</h3>
                  </div>
                <div class="card-body">
                    <form action="{{ route('companies.store') }}" method="post">
                        @csrf
                        @method('post')
                        <x-adminlte-input name="name" label="Name" placeholder="name"
                                fgroup-class="col-md-12"/>

                        <x-adminlte-textarea name="description" fgroup-class="col-md-12"  label="Description" placeholder="description"/>

                        <x-adminlte-button  type="submit" label="submit" class="ml-2" theme="primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/company/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Company')

@section('content_header')
    <h1 class="m-0 text-dark">Companies</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Company - {{ $company->name }}</h3>
                  </div>
                <div class="card-body">
                    <form action="{{ route('companies.update',$company->id) }}" method="post">
                        @csrf
                        @method('put')
                        <x-adminlte-input name="name" label="Name" placeholder="name"
                                fgroup-class="col-md-12" value="{{ $company->name }}"/>

                        <x-adminlte-textarea name="description" fgroup-class="col-md-12"  label="Description" placeholder="description">{{ $company->description }}</x-adminlte-textarea>

                        <x-adminlte-select name="status_id" fgroup-class="col-md-12" label="Status">
                            <x-adminlte-options :options="[1 => 'Active', 0 => 'Inactive']" selected="{{ $company->status_id}}"
                                empty-option="Select one"/>
                        </x-adminlte-select>

                        <x-adminlte-button  type="submit" label="submit" class="ml-2" theme="primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/company/index.blade.php
@extends('adminlte::page')

@section('title', 'Companies')

@section('content_header')
    <h1 class="m-0 text-dark">Companies</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Companies List</h3>
                    <div class="card-tools">
                        <a href="{{ route('companies.create') }}" class="btn btn-primary">Create</a>
                    </div>
                  </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($companies as $company)
                                    <tr>
                                        <td>{{ $company->name }}</td>
                                        <td>{{ $company->description }}</td>
                                        <td>{{ $company->status->name }}</td>
                                        <td>
                                            <a href="{{ route('companies.edit',$company->id) }}" class="btn btn-info">Edit</a>
                                            <a href="{{ route('companies.show',$company->id) }}" class="btn btn-info">Show</a>
                                            
                                            <form  action="{{ route('companies.destroy',$company->id) }}" class="submit-delete-form" method="POST" style="display: inline;"> @csrf @method('delete')
                                                <a href="#" class="btn btn-danger delete">Delete</a>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4" class="text-center">No records</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $companies->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
<script type="text/javascript">

    $('table tbody').on('click','.delete',function(e){
        e.preventDefault();
        var url = $(this).data('route');
        var that = this;

        Swal.fire({
            icon: 'info',
            title: 'Delete Company',
            text: 'Do you really want to delete?',
            showCancelButton: true,
            showConfirmButton:true,
            preConfirm: (res) => {
                that.closest('form').submit();
            }
        })
    });
    
    
</script>
@endpush

resources/views/pages/company/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Company')

@section('content_header')
    <h1 class="m-0 text-dark">Companies</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Company Details - {{ $company->name }}</h3>
                  </div>
                <div class="card-body">
                        <x-adminlte-input name="name" label="Name" placeholder="name"
                                fgroup-class="col-md-12" value="{{ $company->name }}" readonly/>

                        <x-adminlte-textarea name="description" fgroup-class="col-md-12"  label="Description" placeholder="description" readonly>{{ $company->description }}</x-adminlte-textarea>

                        <x-adminlte-select readonly name="status_id" fgroup-class="col-md-12" label="Status">
                            <x-adminlte-options :options="[1 => 'Active', 0 => 'Inactive']" selected="{{ $company->status_id}}"
                                empty-option="Select one"/>
                        </x-adminlte-select>

                        <x-adminlte-input name="name" label="Created At" placeholder="name"
                                fgroup-class="col-md-12" value="{{ $company->created_at }}" readonly/>

                        <a href="{{ route('companies.index')}}" class="btn btn-default ml-2">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop